### ISSUE TITLE
install pstreams library

### ISSUE THREAD

**Issue by jsmedmar** [juanperin/mskcc-hpc#1]
I am trying to install a tool that depends on c++ pstreams libary. I guess I cannot install this myself.

"yum install pstreams-devel" doesn't seem to work.

I am working on luna. I am not sure who I should contact for this request. Any help would be appreciated.

**Comment by juanperin** [comment]
Juan, 

Julia Zhao can help you.  In this case, i’d suggest just emailing for such things.  I didn’t mean to introduce any confusion by creating a separate channel, but application installs and system support should work best at that email address.

If its pretty easy to install, she will take care of it pretty quickly.

**Comment by jsmedmar** [comment]
I appreciate it, thank you Juan.
